name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  FLUTTER_VERSION: '3.24.0'

jobs:
  analyze-and-test:
    name: Analyze & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Analyze
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
        continue-on-error: true  # Continue even if no tests exist

  build-check:
    name: Build Check (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: web
            os: ubuntu-latest
            build-cmd: flutter build web
          - platform: linux
            os: ubuntu-latest
            build-cmd: flutter build linux --debug
            pre-install: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
          - platform: windows
            os: windows-latest
            build-cmd: flutter build windows --debug
          - platform: macos
            os: macos-latest
            build-cmd: flutter build macos --debug
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Linux dependencies
        if: matrix.pre-install
        run: ${{ matrix.pre-install }}
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build ${{ matrix.platform }}
        run: ${{ matrix.build-cmd }}
