name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.0'

# Sets permissions of the GITHUB_TOKEN for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build Web
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Web
        run: flutter build web --release --base-href "/defterim/"
      
      - name: Upload Web build for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  # Deploy to GitHub Pages
  deploy-pages:
    name: Deploy to GitHub Pages
    needs: build-web
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
