// File generated by FlutterFire CLI.
// Run: flutterfire configure
// Or manually add your Firebase configuration here

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


// // Your web app's Firebase configuration
// // For Firebase JS SDK v7.20.0 and later, measurementId is optional
// const firebaseConfig = {
//   apiKey: "AIzaSyBKYfe9HTQpraH1sLkkEDRazCyIDiWKxls",
//   authDomain: "defterim-482110.firebaseapp.com",
//   projectId: "defterim-482110",
//   storageBucket: "defterim-482110.firebasestorage.app",
//   messagingSenderId: "896028980362",
//   appId: "1:896028980362:web:dfc6ca2ff5c82a5eb5e973",
//   measurementId: "G-8PJYR4BDDW"
// };

// // Initialize Firebase
// const app = initializeApp(firebaseConfig);
// const analytics = getAnalytics(app);


  // TODO: Add your Firebase configuration
  // Run: flutterfire configure
  // Or get these from Firebase Console
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKYfe9HTQpraH1sLkkEDRazCyIDiWKxls',
    appId: '1:896028980362:web:dfc6ca2ff5c82a5eb5e973',
    messagingSenderId: '896028980362',
    projectId: 'defterim-482110',
    authDomain: 'defterim-482110.firebaseapp.com',
    storageBucket: 'defterim-482110.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.defterim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.defterim',
  );

  // Windows uses web SDK - same config as web
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKYfe9HTQpraH1sLkkEDRazCyIDiWKxls',
    appId: '1:896028980362:web:dfc6ca2ff5c82a5eb5e973',
    messagingSenderId: '896028980362',
    projectId: 'defterim-482110',
    authDomain: 'defterim-482110.firebaseapp.com',
    storageBucket: 'defterim-482110.firebasestorage.app',
  );

  // Linux uses web SDK - same config as web
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBKYfe9HTQpraH1sLkkEDRazCyIDiWKxls',
    appId: '1:896028980362:web:dfc6ca2ff5c82a5eb5e973',
    messagingSenderId: '896028980362',
    projectId: 'defterim-482110',
    authDomain: 'defterim-482110.firebaseapp.com',
    storageBucket: 'defterim-482110.firebasestorage.app',
  );
}



